# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{heroku-environment}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["David Dollar"]
  s.date = %q{2010-08-12}
  s.description = %q{Push and pull Heroku environments for local use}
  s.email = %q{ddollar@gmail.com}
  s.files = [
    "Rakefile",
     "lib/heroku-environment.rb",
     "lib/heroku/command/config.rb",
     "lib/heroku/environment.rb"
  ]
  s.has_rdoc = false
  s.homepage = %q{http://github.com/ddollar/heroku-environment}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Push and pull Heroku environments for local use}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

